<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\FiscalMonth;
use App\Models\FiscalYear;
use App\Models\GatheringType;
use App\Reports\Attendance\AttendanceData;
use App\Reports\Attendance\AttendancePeriod;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

/**
 * Backs the Attendance Analytics page and the gathering page - separate
 * from the CRUD AttendanceController. Attendance PDF and Excel reports are
 * generated by the report engine (App\Reports\Attendance, POST /reports),
 * from the same AttendanceData these endpoints return.
 */
class AttendanceReportController extends Controller
{
    /**
     * Everything the Attendance Analytics page shows for one church and
     * period (see period() for how a period is given): the summary strip,
     * the Sunday / Ministries / Events / Children tabs and their insights.
     */
    public function analytics(Request $request): JsonResponse
    {
        $resolved = $this->period($request);
        if ($resolved instanceof JsonResponse) {
            return $resolved;
        }
        [$territoryId, $period] = $resolved;

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => (new AttendanceData([$territoryId], $period))->analytics(),
        ]);
    }

    /**
     * One ministry or event over a period, for the gathering page: a
     * configured type (gathering_type_id, which must be this church's) or a
     * one-off named gathering (name).
     */
    public function gathering(Request $request): JsonResponse
    {
        $resolved = $this->period($request, [
            'gathering_type_id' => 'nullable|integer|required_without:name',
            'name' => 'nullable|string|max:255|required_without:gathering_type_id',
        ]);
        if ($resolved instanceof JsonResponse) {
            return $resolved;
        }
        [$territoryId, $period] = $resolved;

        $type = null;
        if ($request->filled('gathering_type_id')) {
            $type = GatheringType::with('category')->whereKey($request->query('gathering_type_id'))->where('territory_id', $territoryId)->first();
            if (! $type) {
                return response()->json([
                    'success' => false,
                    'status' => 422,
                    'message' => 'That gathering type does not belong to this church.',
                    'errors' => ['gathering_type_id' => ['Invalid gathering type for this church.']],
                ], 422);
            }
        }

        $detail = (new AttendanceData([$territoryId], $period))->gatheringDetail($type, $type ? null : $request->query('name'));
        if (! $detail) {
            return response()->json(['success' => false, 'status' => 404, 'message' => 'Nothing has been recorded under that name.'], 404);
        }

        return response()->json(['success' => true, 'status' => 200, 'data' => $detail]);
    }

    /**
     * Ownership + the period a request asks for: a fiscal year (or all), one
     * month of it (fiscal_month_id or month=1-12), or a range of months
     * (from/to as YYYY-MM).
     *
     * @return JsonResponse|array{0: int, 1: AttendancePeriod}
     */
    private function period(Request $request, array $extraRules = []): JsonResponse|array
    {
        $territoryId = (int) $request->query('territory_id');
        if (! $territoryId || ! $this->userOwnsChurch($request->user(), $territoryId)) {
            return response()->json([
                'success' => false,
                'status' => 403,
                'message' => 'You do not have access to this church\'s attendance.',
            ], 403);
        }

        $validator = Validator::make($request->all(), [
            'from' => ['nullable', 'date_format:Y-m', 'required_with:to'],
            'to' => ['nullable', 'date_format:Y-m', 'required_with:from', 'after_or_equal:from'],
            'fiscal_year_id' => ['nullable', 'required_without:from', function ($attribute, $value, $fail) {
                if ($value !== 'all' && ! FiscalYear::whereKey($value)->exists()) {
                    $fail('Choose a year, or all time.');
                }
            }],
            'fiscal_month_id' => 'nullable|exists:fiscal_months,id',
            'month' => 'nullable|integer|between:1,12',
            ...$extraRules,
        ]);
        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'status' => 422,
                'message' => 'Validation error',
                'errors' => $validator->errors(),
            ], 422);
        }

        if ($request->filled('from')) {
            return [$territoryId, AttendancePeriod::range($request->query('from'), $request->query('to'))];
        }

        $yearId = $request->query('fiscal_year_id');
        // A month by id, or by number (1-12) - the pages only know the number.
        $monthId = match (true) {
            $yearId === 'all' => null,
            $request->filled('fiscal_month_id') => (int) $request->query('fiscal_month_id'),
            $request->filled('month') => FiscalMonth::where('number', (int) $request->query('month'))->value('id'),
            default => null,
        };

        return [$territoryId, AttendancePeriod::resolve($yearId === 'all' ? 'all' : (int) $yearId, $monthId, [$territoryId])];
    }

    /**
     * Same ownership check as AttendanceController - each controller keeps
     * its own copy rather than sharing a trait, matching this codebase's
     * existing per-controller convention (see AttendanceController,
     * DemographicsController).
     */
    private function userOwnsChurch($user, int $territoryId): bool
    {
        if ($user->hasGlobalAccess()) {
            return true;
        }

        return $user->activeAssignments()
            ->where('territory_id', $territoryId)
            ->exists();
    }
}
