<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\FiscalMonth;
use App\Models\FiscalYear;
use App\Reports\Attendance\AttendanceData;
use App\Reports\Attendance\AttendancePeriod;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

/**
 * Backs the Attendance Analytics page - separate from the CRUD
 * AttendanceController. Attendance PDF and Excel reports are generated by
 * the report engine (App\Reports\Attendance, POST /reports), from the same
 * AttendanceData this endpoint returns.
 */
class AttendanceReportController extends Controller
{
    /**
     * Everything the Attendance Analytics page shows for one church and
     * period (a fiscal year, a month of it, or fiscal_year_id=all): the
     * summary strip, the Sunday / Ministries / Events / Children tabs and
     * (month narrows a year to one month: fiscal_month_id or month=1-12)
     * their insights - built by AttendanceData, the same numbers the
     * attendance PDF and Excel reports use.
     */
    public function analytics(Request $request): JsonResponse
    {
        $territoryId = (int) $request->query('territory_id');
        if (! $territoryId || ! $this->userOwnsChurch($request->user(), $territoryId)) {
            return response()->json([
                'success' => false,
                'status' => 403,
                'message' => 'You do not have access to this church\'s attendance.',
            ], 403);
        }

        $validator = Validator::make($request->all(), [
            // A range of months (from/to, YYYY-MM) instead of a year.
            'from' => ['nullable', 'date_format:Y-m', 'required_with:to'],
            'to' => ['nullable', 'date_format:Y-m', 'required_with:from', 'after_or_equal:from'],
            'fiscal_year_id' => ['nullable', 'required_without:from', function ($attribute, $value, $fail) {
                if ($value !== 'all' && ! FiscalYear::whereKey($value)->exists()) {
                    $fail('Choose a year, or all time.');
                }
            }],
            'fiscal_month_id' => 'nullable|exists:fiscal_months,id',
            'month' => 'nullable|integer|between:1,12',
        ]);
        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'status' => 422,
                'message' => 'Validation error',
                'errors' => $validator->errors(),
            ], 422);
        }

        if ($request->filled('from')) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'data' => (new AttendanceData([$territoryId], AttendancePeriod::range($request->query('from'), $request->query('to'))))->analytics(),
            ]);
        }

        $yearId = $request->query('fiscal_year_id');
        // A month by id, or by number (1-12) - the page only knows the number.
        $monthId = match (true) {
            $yearId === 'all' => null,
            $request->filled('fiscal_month_id') => (int) $request->query('fiscal_month_id'),
            $request->filled('month') => FiscalMonth::where('number', (int) $request->query('month'))->value('id'),
            default => null,
        };
        $period = AttendancePeriod::resolve($yearId === 'all' ? 'all' : (int) $yearId, $monthId, [$territoryId]);

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => (new AttendanceData([$territoryId], $period))->analytics(),
        ]);
    }

    /**
     * Same ownership check as AttendanceController - each controller keeps
     * its own copy rather than sharing a trait, matching this codebase's
     * existing per-controller convention (see AttendanceController,
     * DemographicsController).
     */
    private function userOwnsChurch($user, int $territoryId): bool
    {
        if ($user->hasGlobalAccess()) {
            return true;
        }

        return $user->activeAssignments()
            ->where('territory_id', $territoryId)
            ->exists();
    }
}
